config/routes.rb
Rails.application.routes.draw do

root "home#index"

get "page1" => "home#page1"

get "page2" => "home#page2"

get "page3" => "home#page3"

get "dashboard" => "home#dashboard"

get "withdraw" => "home#withdraw"

get "confirm" => "home#confirm"

get "addfunds" => "home#addfunds"

get "addbank" => "home#addbank"

get "settings" => "home#settings"


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController



def index
    render :layout => "landing_page"
end

def page1
end

def page2
end

def dashboard
	render :layout => "dashboard"
end

def page3
    render :layout => "business"
end


def withdraw
	render :layout => "dashboard"
end

def confirm
	render :layout => "dashboard"
end

def page3
    render :layout => "business"
end

def addfunds
    render :layout => "dashboard"
end

def addbank
    render :layout => "dashboard"
end

def settings
    render :layout => "dashboard"
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/addbank.html.erb
<div class=".centered-container ng-scope">
  <ng-switch on="model.category">
    <!-- ngSwitchWhen: BANK_DOC --><div ng-switch-when="BANK_DOC" class="ng-scope">
      <!-- ngInclude: undefined --><ng-include src="'uploads/partials/bank_statement.html'" class="ng-scope"><h2 class="ng-binding ng-scope">Add a bank account</h2>

<div class="ng-binding ng-scope">
  Please upload one of the following:
  <ul>
    <li ng-show="false" class="ng-binding ng-hide">A PDF or image copy of your full bank statement</li>
    <li ng-show="false" class="ng-binding ng-hide">An image of a cleared cheque</li>
    <li ng-hide="false" class="ng-binding">The first page of your bank statement</li>
    <li ng-hide="false" class="ng-binding">An image of a void cheque</li>
    <li translate="uploads.bank-docs.doc-types.UploadedDocument::BankScreenshot.description" class="ng-scope">A screenshot of your online banking account clearly showing your full name, bank’s logo, <strong>complete account and transit number</strong>, and the current balance in your account</li>
  </ul>
</div>
</ng-include>
    </div><!-- end ngSwitchWhen: -->
    <!-- ngSwitchDefault:  -->
  </ng-switch>
  <div class="direct-upload">
    <div class="progress">
      <div class="progress-bar" style="width:%" ng-class="{'error': model.hasError || model.isInvalidFileType}"></div>
    </div>
    <form class="upload-form base-margin-bottom-x2 ng-pristine ng-valid" enctype="multipart/form-data" accept-charset="UTF-8" method="post">
      <div class=".upload-error ng-binding ng-hide" ng-show="model.hasError">
        There was an issue uploading the provided document. Please try again later.
      </div>
      <div class=".upload-error ng-binding ng-hide" ng-show="model.isInvalidFileType">
        The document type you uploaded is not supported. Try using a PDF or image file (jpeg, png)
      </div>
      <input type="file" ngf-select="uploadFile($file, selected)" accept="image/*,application/pdf" c2cf="">
    </form>
  </div>
  <p translate="uploads.help.questions" translate-values="{link: nav.location.submitRequest}" class="ng-scope">Questions? Send us <a href="http://help.wealthsimple.com/hc/en-us/requests/new" target:"_blank"="">a note</a> for help.</p>
  <p ng-show="true" class="ng-binding">
    If you do not have access to any of the things listed above, you can mail in a $1 cheque to:
    </p><p class="ng-binding">860 Richmond Street West, 3rd floor<br>Toronto, ON, M6J 1C9, Canada</p>
  <p></p>
  </div>
  </div>

app/views/home/addfunds.html.erb
<div ng-controller="WS.FundingController" class="ng-scope">
<!-- ngInclude: 'funding/index.html' --><div ng-include="'funding/index.html'" class="ng-scope"><h2 class="ng-binding ng-scope">Hello, David!</h2>

<p class="ng-binding ng-scope">Thanks for setting up your account. We're now ready for you to transfer funds to your TFSA! Fund your account using your chequing account or transfer an existing account to Wealthsimple.</p>
<!-- ngInclude: 'funding/eft-section.html' --><div ng-show="portfolio.eft_eligible" ng-include="'funding/eft-section.html'" class="ng-scope"><div class="row-md funding-method-container ng-scope">

  <div class="col-3">
    <h4 class="inline-header-md">Electronic funds transfers</h4>
  </div>

  <div class="col-9">
    <p>
      This is the fastest and easiest way to transfer and start investing your funds. Enter the amount and frequency of contributions below to start a new transfer.
    </p>

    <!-- ngInclude: 'funding/eft-form.html' --><div ng-include="'funding/eft-form.html'" class="ng-scope"><form name="fundingForm" ng-submit="submit(fundingForm)" novalidate="" class="ng-scope ng-invalid ng-invalid-required ng-dirty ng-valid-parse">
  <div class="row-sm form-row">
    <div class="col-3">
      <input class="form-input-text size-sm ng-pristine ng-invalid ng-invalid-required ng-touched" type="text" name="amount" placeholder="$0" ng-model="fundingRequest.amount" money="" required="" min-value="1" max-value="1000000" focus="" autocomplete="off">
      <!-- ngIf: fundingForm.amount.$dirty -->
    </div>
    <div class="col-3">
      <select class="form-control size-sm ng-pristine ng-untouched ng-valid" name="frequency" ng-model="fundingRequest.frequency">
        <option value="monthly" selected="">Every month</option>
        <option value="every_other_week">Every two weeks</option>
        <option value="weekly">Every week</option>
        <option value="once">Just this once</option>
      </select>
    </div>
    <div class="col-3">
      <select class="form-control size-sm ng-pristine ng-untouched ng-valid" name="frequency" ng-model="fundingRequest.frequency">
        <option value="monthly" selected="">Funding Source</option>
        <option value="every_other_week">CIBC ****3213</option>
        <option value="weekly">RBC ****3052</option>
      </select>
    </div>
    <div class="col-3">
      <button class="button primary-action size-md ng-binding" type="submit" ng-disabled="fundingForm.$invalid || fundingForm.submitting" disabled="disabled"> Submit </button>
    </div>
  </div>
</form></div>

    <table class="table-opaque" ng-show="efts.length > 0 || pacs.length > 0">
      <thead>
        <tr>
          <th class="status-column"></th>
          <th>Creation Date</th>
          <th>From</th>
          <th>Amount</th>
          <th>Frequency</th>
          <th>Status</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <!-- ngRepeat: pac in pacs -->
        <!-- ngRepeat: eft in efts --><tr ng-repeat="eft in efts" class="ng-scope">
          <td ng-class="['status-column', eft.status_category]" class="status-column success">
          </td>
          <td class="ng-binding">Apr 17, 2016</td>
          <td class="ng-binding">CIBC</td>
          <td class="ng-binding">$100</td>
          <td>One time</td>
          <td class="ng-binding">Processed</td>
        </tr><!-- end ngRepeat: eft in efts --><tr ng-repeat="eft in efts" class="ng-scope">
          <td ng-class="['status-column', eft.status_category]" class="status-column success">
          </td>
          <td class="ng-binding">Mar 16, 2016</td>
          <td class="ng-binding">CIBC</td>
          <td class="ng-binding">$50</td>
          <td>One time</td>
          <td class="ng-binding">Processed</td>
        </tr><!-- end ngRepeat: eft in efts --><tr ng-repeat="eft in efts" class="ng-scope">
          <td ng-class="['status-column', eft.status_category]" class="status-column success">
          </td>
          <td class="ng-binding">Mar 15, 2016</td>
          <td class="ng-binding">CIBC</td>
          <td class="ng-binding">$50</td>
          <td>One time</td>
          <td class="ng-binding">Processed</td>
        </tr><!-- end ngRepeat: eft in efts -->
      </tbody>
    </table>

    <!-- ngInclude: 'funding/promo-section.html' --><div ng-include="'funding/promo-section.html'" class="ng-scope"><div class="promo-section ng-scope ng-hide" ng-show="viewData.eftsAndPacsLoaded &amp;&amp; userPromos.length > 0 &amp;&amp; efts.length === 0 &amp;&amp; pacs.length === 0">
  <!-- TODO: eventually build a UI to handle multiple promos per user -->
  <p class="promo-message ng-binding"></p>
</div></div>
  </div>
</div></div>
<div ng-show="!viewData.anyBankAccountsRequireDocuments" class="ng-scope">
  <!-- ngInclude: 'funding/bank-account-section.html' --><div ng-include="'funding/bank-account-section.html'" class="ng-scope"><div class="row-md funding-method-container ng-scope" data-ng-show="viewData.bankAccountsLoaded">

  <div class="col-3">
    <h4 class="inline-header-md">Bank accounts</h4>
  </div>

  <div class="col-9">

    <div data-ng-show="bankAccounts.length > 0" class="">
      <p>
        Wealthsimple investment accounts can accept fund transfers from bank accounts that are in your name and that have been verified by our compliance department. Here's what we have on file for you:
      </p>

      <table class="table-opaque">
        <thead>
          <tr>
            <th class="status-column"></th>
            <th>Bank</th>
            <th>Institution</th>
            <th>Transit</th>
            <th>Account</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <!-- ngRepeat: bankAccount in bankAccounts --><tr ng-repeat="bankAccount in bankAccounts" class="ng-scope">
            <td ng-class="['status-column', bankAccount.status_category]" class="status-column success"></td>
            <td class="ng-binding">CIBC</td>
            <td class="ng-binding">010</td>
            <td class="ng-binding">***4582</td>
            <td class="ng-binding">***8698</td>
            <td ng-switch="bankAccount.status">
              <!-- ngSwitchWhen: verified --><span ng-switch-when="verified" class="ng-scope">Verified</span><!-- end ngSwitchWhen: -->
              <!-- ngSwitchWhen: document_required -->
              <!-- ngSwitchDefault:  -->
            </td>
          </tr><!-- end ngRepeat: bankAccount in bankAccounts -->
        </tbody>
      </table>
      <p ng-if="transfers" class="ng-scope">
      <%= link_to "+ Add a Bank Account", addbank_path, :class => "table-link" %>
    </p>
    </div>

  </div>

</div></div>
</div>
<!-- ngInclude: 'funding/transfer-section.html' --><div ng-include="'funding/transfer-section.html'" class="ng-scope"><div class="row-md funding-method-container ng-scope">
  <div class="col-3">
    <h4 class="inline-header-md">Transfer existing accounts</h4>
  </div>
  <div class="col-9">
    <p class="ng-binding">
      If you already have a TFSA account with another financial institution, you can transfer it to Wealthsimple.
    </p>
    <!-- ngIf: !transfers -->
    <!-- ngIf: transfers --><table ng-if="transfers" class="table-opaque ng-scope">
      <thead>
        <tr>
          <th>Date</th>
          <th>Institution</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <!-- ngRepeat: transfer in transfers -->
      </tbody>
    </table><!-- end ngIf: transfers -->
    <!-- ngIf: transfers --><p ng-if="transfers" class="ng-scope">
      <a href="/app/portfolios/tfsa-8r-jo_-3/transfer/new" class="table-link">+ Set up transfer</a>
    </p><!-- end ngIf: transfers -->
  </div>
</div></div></div>
</div></div>

app/views/home/index.html.erb
<div class="container-padded">
<div class="container-hero">

		<div class="index-hero-header">
			Take care of your employees.
		</div>	
		<%= link_to "Get started today", page1_path, class: "index-hero-button" %>
</div>

<div class="index-hero-bg">
		<div class="announcement-banner-image-and-text-container">	 
			<div class="announcement-banner-image">
			</div>

		<div class="announcement-banner-text-container">
			<h2 class="announcement-banner-header">We're celebrating $400 million under management
			</h2>
			<div class="announcement-banner-text">
            Over 10,000 Canadians are using Wealthsimple
          	</div>
		</div>
	</div>
</div>

<div class="announcement-banner"></div>

<div class="about-Section1">
	<div class="container2">
		<div class="about-Title">How Wealthsimple can help your business</div>

		<div class="about-item-content">
			<div class="about-item">
				<div class="about-image"></div>
				<div class="about-content">
					<div class="about-ui-header">
                    Open a beautiful storefront
                  </div>
					Sell your digital products through a customizable store and product pages that will look great on both desktop and mobile.
				</div>
			</div>

			<div class="about-item">
				<div class="about-image"></div>
				<div class="about-content">
					<div class="about-ui-header">
                    Open a beautiful storefront
                  </div>
					Sell your digital products through a customizable store and product pages that will look great on both desktop and mobile.
				</div>
			</div>

			<div class="about-item">
				<div class="about-image"></div>
				<div class="about-content">
					<div class="about-ui-header">
                    Open a beautiful storefront
                  </div>
					Sell your digital products through a customizable store and product pages that will look great on both desktop and mobile.
				</div>
			</div>
		</div>
			<div class="about-illustration">
			</div>


	</div>
</div>





<!--<div class="about-Section2">
	<div class="container2">
		<div class="about-Title2">Simple Pricing</div>
		<div class="about-Subtitle">0.5% Fee. Nothing more.</div>
		<%= link_to "Get started today", page1_path, class: "index-hero-button2" %>
	</div>
</div>


<div class="about-Section1">
	<div class="container2">
		<div class="about-Title">Frequently Asked Questions </div>

<div class="panel-group" id="accordion">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title">
				<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Collapsible Group Item #1</a>
			</h4>
		</div>
		<div id="collapseOne" class="panel-collapse collapse in">
			<div class="panel-body">
				Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
			</div>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title">
				<a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Collapsible Group Item #2</a>
			</h4>
		</div>
		<div id="collapseTwo" class="panel-collapse collapse">
			<div class="panel-body">
				Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
			</div>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title">
				<a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">Collapsible Group Item #3</a>
			</h4>
		</div>
		<div id="collapseThree" class="panel-collapse collapse">
			<div class="panel-body">
				Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
			</div>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 class="panel-title">
				<a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Collapsible Group Item #2</a>
			</h4>
		</div>
		<div id="collapseTwo" class="panel-collapse collapse">
			<div class="panel-body">
				Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
			</div>
		</div>
	</div>

</div>
</div>
</div>-->




</div>




<div class="container-yellow">
	<h2 class="base-margin-bottom-x3">
      What are you waiting for? 
  </br>
      Get started.
  </h2>

<div class="base-margin-bottom-x4">
      Whether you're here to set up a long term investment plan or just make your everyday life sweeter. Get going.
</div>


<%= link_to "Create a business account", page1_path, class: "button-large" %>






</div>




app/views/home/page1.html.erb
<div class="centered-form-container">
	<h1>Let's get started</h1>
	<h2>Create an account and start your plan today</h2>

	<div class="form-box">
		<div class="form-input">
			<input class="form-half-left", placeholder="First name">
			</input>
			<input class="form-half-right", placeholder="Last name">
			</input>
		</div>



		<div class="form-input">
			<input class="form-half-left", placeholder="Email">
			</input>
			<input class="form-half-right", placeholder="Phone number">
			</input>
		</div>

		<div class="form-input">
			<input class="form-full", placeholder="Password">
			</input>
		</div>

		<div class="form-input">
			<%= link_to "Create Business Account", page2_path, class: "submit-Btn2" %>
		</div>
	</div>

</div>




app/views/home/page2.html.erb
<div class="centered-form-container">
	<h1>One last step to go</h1>
	<h2>Set up your company profile</h2>

	<div class="form-box">
		<div class="upload-logo">
			Upload Your Logo
		</div>


		<div class="form-input">
			<input class="form-full", placeholder="Company name">
			</input>
		</div>

		<div class="form-input">
			<input class="form-full", placeholder="Number of employees">
			</input>
		</div>


		<div class="form-input">
			<input class="form-triple", placeholder="Write a message for your employees">
			</input>
		</div>

		<h2>Share the link below with your employees</h2>

		<div class="form-input">
			<input class="form-full", placeholder="yourbusiness.wealthsimple.com">
			</input>
		</div>
		<div class="form-input">
			<%= link_to "Save", page3_path, class: "submit-Btn2" %>
		</div>
	</div>

</div>

app/views/home/page3.html.erb




<div class="template-container">
</div>

<div class="profile-content">
	<div class="profile-image">
	</div>

	<h2 class="profile-name">Your Company Name</h2>
	<div class="profile-bio">Finance guy turned Entrepreneur

CEO of Tunezy, a social e-commece platform for Music

Executive-in-Residence (EiR) at the University of Toronto

Profit Magazine Top 20 under 30 Entrepreneur

Formerly with CIBC World Markets in Equity Derivative Sales & FX Trading
<div class="profile-linkbar">
	<div class="profile-link1">Create your account</div>

<%= link_to Wealthsimple, root_path, class: "profile-logo" %>
</div>
</div>
</div>

app/views/home/withdraw.html.erb
<div class="centered-form-container">
	<h1>Request a Withdraw</h1>
	<h2>Withdraw Funds To Your Bank</h2>

	<div class="form-box">
		<div class="form-input">
		<label class="checkbox-container base-padding-bottom ng-binding" style="    float: left;
    margin-right: 20px;">
        <div class="checkbox-fancy checked" style="position: relative;"><input type="checkbox" name="email_updates" ng-model="user.email_updates" class="ng-pristine ng-untouched ng-valid ng-not-empty" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins></div>
        TFSA - $12,849.49
      </label>
		<label class="checkbox-container base-padding-bottom ng-binding" style="    float: left;
    margin-right: 20px;">
        <div class="checkbox-fancy" style="position: relative;"><input type="checkbox" name="email_updates" ng-model="user.email_updates" class="ng-untouched ng-valid ng-empty ng-dirty ng-valid-parse" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins></div>
        RRSP - $60,456.00
      </label>
      <div class="col-3">
      <select class="form-control size-sm ng-pristine ng-valid ng-touched" name="frequency" ng-model="fundingRequest.frequency">
        <option value="monthly" selected="">Choose Account</option>
        <option value="every_other_week">CIBC Checking ****7756</option>
        <option value="weekly">RBC Saving ****4782</option>
      </select>
    </div>
			<input class="form-full", placeholder="Amount to withdraw">
			</input>
		</div>

		<h2>You will receive a confirmation email upon submission. Withdrawals can take up to 2-5 business days to process</h2>
		<div class="form-input">
			<%= link_to "Submit Request", confirm_path, class: "submit-Btn2" %>
		</div>
	</div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wealthsimple | Smart investing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <meta content="https://my.wealthsimple.com/apple-touch-icon.png" property="og:image">
  <script src="https://use.typekit.net/wca0ytu.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
</head>



<div class="container-padded">
	<div class="navbar2">

		<%= link_to Wealthsimple, root_path, class: "nav-logo" %>

		<div class="nav-pullright">
			<div class="navigation-item">
				<div class="button-yellow">
					Get started
				</div>
			</div>

			<div class="main-nav-navigation-item">
				Sign in
			</div>

			<div class="main-nav-navigation-item">
				How it works
			</div>

			<div class="main-nav-navigation-item">
				Why invest
			</div>
		</div>
	</div>














<body>

<%= yield %>

</body>
	</div>
</html>

app/views/layouts/business.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wealthsimple | Smart investing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>

<body>

<%= yield %>

</body>

</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wealthsimple | Smart investing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>



<div class="container-padded">
	<div class="navbar2">

		<%= link_to Wealthsimple, root_path, class: "nav-logo" %>

		<div class="nav-pullright">
			<div class="navigation-item">
				<div class="button-yellow">
					Get started
				</div>
			</div>

			<div class="main-nav-navigation-item">
				Sign in
			</div>

			<div class="main-nav-navigation-item">
				How it works
			</div>

			<div class="main-nav-navigation-item">
				Why invest
			</div>
		</div>
	</div>
</div>


<body>

<%= yield %>

</body>

</html>